---
version: '3'

services:
  temper:
    container_name: temper
    hostname: temper
    image: temper/service:latest
    volumes:
      - /dev:/dev
    restart: always
    ports:
      - 2610:2610
    privileged: true
    deploy:
      resources:
        limits:
          memory: 32M
